r = float(input("Rent per month:"))
g = float(input("Gas payment per month:"))
e = float(input("Electricity per month:"))
w = float(input("Water payment per month:"))
c = float(input("Council tax per month:"))
print("Your monthly expenses are:")
t = float(r + g + e + w + c)

print("Rent:","£".rjust(13),str(r).center(9))
print("Gas:","£".rjust(14),str(g).center(9))
print("Electricity:","£".rjust(6),str(e).center(9))
print("Water:","£".rjust(12),str(w).center(10))
print("Council Tax:","£".rjust(6),str(c).center(10))
print("=".center(26, "="))
print("Total:","£".rjust(12),str(t).center(9))